addressfield_lookup_postcodeanywhere.settings:
  type: mapping
  label: Settings
  mapping:
    addressfield_lookup_postcodeanywhere_login:
      type: string
    addressfield_lookup_postcodeanywhere_country_quality:
      type: integer
